services:
  - type: web
    name: hotel-management-api
    runtime: dotnet
    rootDir: DEV-FE-BE/backend/be-quanlikhachsanapi
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/be-quanlikhachsanapi.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:$PORT