import '../../styles/globals.css';
import type { Metadata } from 'next';
import '@fortawesome/fontawesome-free/css/all.min.css';

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function CusAccLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}