// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using be_quanlikhachsanapi.Data;

#nullable disable

namespace be_quanlikhachsanapi.Migrations
{
    [DbContext(typeof(QuanLyKhachSanContext))]
    partial class QuanLyKhachSanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("be_quanlikhachsanapi.Data.ApDungKm", b =>
                {
                    b.Property<string>("MaApDung")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaDatPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaKm")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKM");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaApDung");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaKm");

                    b.ToTable("ApDungKM", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.BaoCaoDoanhThu", b =>
                {
                    b.Property<string>("MaBaoCao")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("TongDatPhong")
                        .HasColumnType("int");

                    b.Property<int>("TongDichVuDaSuDung")
                        .HasColumnType("int");

                    b.Property<decimal>("TongDoanhThu")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaBaoCao")
                        .HasName("PK_BaoCao");

                    b.HasIndex("MaNv");

                    b.ToTable("BaoCaoDoanhThu", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.CaLamViec", b =>
                {
                    b.Property<string>("MaCaLam")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCaLam")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaCaLam");

                    b.ToTable("CaLamViec", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.ChiTietDatPhong", b =>
                {
                    b.Property<string>("MaChiTietDatPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("GiaTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaDatPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("SoDem")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChiTietDatPhong");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiTietDatPhong", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.DatPhong", b =>
                {
                    b.Property<string>("MaDatPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("datetime");

                    b.Property<int?>("NguoiLon")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongPhong")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGianDen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.Property<int?>("TreEm")
                        .HasColumnType("int");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("MaKh");

                    b.ToTable("DatPhong", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.DichVu", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.HoaDon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("GiamGiaLoaiKh")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("GiamGiaLoaiKH");

                    b.Property<decimal?>("GiamGiaLoaiKm")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("GiamGiaLoaiKM");

                    b.Property<string>("MaDatPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaKm")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKM");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoTienConThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SoTienDaThanhToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SoTienThanhToanDu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chưa thanh toán");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaKm");

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("DiaChi")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HoKH");

                    b.Property<string>("MaLoaiKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaLoaiKH");

                    b.Property<string>("MaRole")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("SoCccd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SoCCCD");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenKH");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKh");

                    b.HasIndex("MaLoaiKh");

                    b.HasIndex("MaRole");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.KhuyenMai", b =>
                {
                    b.Property<string>("MaKm")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaKM");

                    b.Property<string>("MaGiamGia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<int>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("MaKm");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.LoaiKhachHang", b =>
                {
                    b.Property<string>("MaLoaiKh")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaLoaiKH");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenLoaiKh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenLoaiKH");

                    b.Property<string>("UuDai")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaLoaiKh");

                    b.ToTable("LoaiKhachHang", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoaiPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("GiaMoiDem")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaMoiGio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("GiuongDoi")
                        .HasColumnType("int");

                    b.Property<int?>("GiuongDon")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KichThuocPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoGiuongNgu")
                        .HasColumnType("int");

                    b.Property<int>("SoPhongTam")
                        .HasColumnType("int");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiPhong");

                    b.ToTable("LoaiPhong", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoNv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HoNV");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("MaCaLam")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenNV");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaNv");

                    b.HasIndex("MaCaLam");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.PhanQuyenNhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MaRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MaNv");

                    b.HasIndex("MaRole");

                    b.ToTable("PhanQuyenNhanVien", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Trống");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoaiPhong");

                    b.ToTable("Phong", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.PhuongThucThanhToan", b =>
                {
                    b.Property<string>("MaPhuongThucThanhToan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("PhuongThucThanhToan");

                    b.Property<decimal>("SoTienCanThanhToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhuongThucThanhToan");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("PhuongThucThanhToan", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.Review", b =>
                {
                    b.Property<string>("MaReview")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BinhLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DanhGia")
                        .HasColumnType("int");

                    b.Property<string>("MaDatPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaReview")
                        .HasName("PK_DanhGia");

                    b.HasIndex("MaDatPhong");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.Role", b =>
                {
                    b.Property<string>("MaRole")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenRole")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaRole")
                        .HasName("PK_Roles");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.SuDungDichVu", b =>
                {
                    b.Property<string>("MaSuDung")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaDatPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaDichVu")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<byte[]>("ThoiGianSuDung")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaSuDung");

                    b.HasIndex("MaDatPhong");

                    b.HasIndex("MaDichVu");

                    b.ToTable("SuDungDichVu", (string)null);
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.ApDungKm", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.DatPhong", "MaDatPhongNavigation")
                        .WithMany("ApDungKms")
                        .HasForeignKey("MaDatPhong")
                        .IsRequired()
                        .HasConstraintName("FK_ApDungKM_DatPhong");

                    b.HasOne("be_quanlikhachsanapi.Data.KhuyenMai", "MaKmNavigation")
                        .WithMany("ApDungKms")
                        .HasForeignKey("MaKm")
                        .IsRequired()
                        .HasConstraintName("FK_ApDungKM_KhuyenMai");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaKmNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.BaoCaoDoanhThu", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.NhanVien", "MaNvNavigation")
                        .WithMany("BaoCaoDoanhThus")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK_BaoCaoDoanhThu_NhanVien");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.ChiTietDatPhong", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.DatPhong", "MaDatPhongNavigation")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaDatPhong")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDatPhong_DatPhong");

                    b.HasOne("be_quanlikhachsanapi.Data.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaLoaiPhong")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDatPhong_LoaiPhong");

                    b.HasOne("be_quanlikhachsanapi.Data.Phong", "MaPhongNavigation")
                        .WithMany("ChiTietDatPhongs")
                        .HasForeignKey("MaPhong")
                        .HasConstraintName("FK_ChiTietDatPhong_Phong");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaLoaiPhongNavigation");

                    b.Navigation("MaPhongNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.DatPhong", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.KhachHang", "MaKhNavigation")
                        .WithMany("DatPhongs")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_DatPhong_KhachHang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.HoaDon", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.DatPhong", "MaDatPhongNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaDatPhong")
                        .IsRequired()
                        .HasConstraintName("FK_HoaDon_DatPhong");

                    b.HasOne("be_quanlikhachsanapi.Data.KhuyenMai", "MaKmNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKm")
                        .HasConstraintName("FK_HoaDon_KhuyenMai");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaKmNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.KhachHang", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.LoaiKhachHang", "MaLoaiKhNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaLoaiKh")
                        .HasConstraintName("FK_KhachHang_LoaiKhachHang");

                    b.HasOne("be_quanlikhachsanapi.Data.Role", "MaRoleNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaRole")
                        .HasConstraintName("FK_KhachHang_Role");

                    b.Navigation("MaLoaiKhNavigation");

                    b.Navigation("MaRoleNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.NhanVien", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.CaLamViec", "MaCaLamNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCaLam")
                        .IsRequired()
                        .HasConstraintName("FK_NhanVien_CaLamViec");

                    b.Navigation("MaCaLamNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.PhanQuyenNhanVien", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.NhanVien", "MaNvNavigation")
                        .WithOne("PhanQuyenNhanVien")
                        .HasForeignKey("be_quanlikhachsanapi.Data.PhanQuyenNhanVien", "MaNv")
                        .IsRequired()
                        .HasConstraintName("FK_PhanQuyen_NhanVien");

                    b.HasOne("be_quanlikhachsanapi.Data.Role", "MaRoleNavigation")
                        .WithMany("PhanQuyenNhanViens")
                        .HasForeignKey("MaRole")
                        .IsRequired()
                        .HasConstraintName("FK_PhanQuyen_Role");

                    b.Navigation("MaNvNavigation");

                    b.Navigation("MaRoleNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.Phong", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.LoaiPhong", "MaLoaiPhongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoaiPhong")
                        .IsRequired()
                        .HasConstraintName("FK_Phong_LoaiPhong");

                    b.Navigation("MaLoaiPhongNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.PhuongThucThanhToan", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.HoaDon", "MaHoaDonNavigation")
                        .WithMany("PhuongThucThanhToans")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK_PhuongThucThanhToan_HoaDon");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.Review", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.DatPhong", "MaDatPhongNavigation")
                        .WithMany("Reviews")
                        .HasForeignKey("MaDatPhong")
                        .IsRequired()
                        .HasConstraintName("FK_Review_DatPhong");

                    b.Navigation("MaDatPhongNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.SuDungDichVu", b =>
                {
                    b.HasOne("be_quanlikhachsanapi.Data.DatPhong", "MaDatPhongNavigation")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDatPhong")
                        .HasConstraintName("FK_SuDungDichVu_DatPhong");

                    b.HasOne("be_quanlikhachsanapi.Data.DichVu", "MaDichVuNavigation")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDichVu")
                        .HasConstraintName("FK_SuDungDichVu_DichVu");

                    b.Navigation("MaDatPhongNavigation");

                    b.Navigation("MaDichVuNavigation");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.CaLamViec", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.DatPhong", b =>
                {
                    b.Navigation("ApDungKms");

                    b.Navigation("ChiTietDatPhongs");

                    b.Navigation("HoaDons");

                    b.Navigation("Reviews");

                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.DichVu", b =>
                {
                    b.Navigation("SuDungDichVus");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.HoaDon", b =>
                {
                    b.Navigation("PhuongThucThanhToans");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.KhachHang", b =>
                {
                    b.Navigation("DatPhongs");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.KhuyenMai", b =>
                {
                    b.Navigation("ApDungKms");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.LoaiKhachHang", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.LoaiPhong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");

                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.NhanVien", b =>
                {
                    b.Navigation("BaoCaoDoanhThus");

                    b.Navigation("PhanQuyenNhanVien");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.Phong", b =>
                {
                    b.Navigation("ChiTietDatPhongs");
                });

            modelBuilder.Entity("be_quanlikhachsanapi.Data.Role", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("PhanQuyenNhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
